// Keyword audit — step 5 deliverables. Merges kw-candidates.json + kw-metrics.json and writes
// keyword-audit.md, keyword-opportunities.md, keyword-candidates.json to repo root.
import fs from "node:fs";
const SC = "C:/Users/PFrew/AppData/Local/Temp/claude/C--Users-PFrew-Projects-Healthypets/45472aec-64cb-486e-b7e4-e7e8457cf953/scratchpad/";
const cand = JSON.parse(fs.readFileSync(SC + "kw-candidates.json", "utf8"));
const M = JSON.parse(fs.readFileSync(SC + "kw-metrics.json", "utf8"));
const met = (k) => M[k] || { v: 0, kd: null, intent: null };

// enrich each page
const pages = cand.pages.map((p) => {
  const cs = p.candidates.map((c) => ({ ...c, ...met(c.kw) })).sort((a, b) => b.v - a.v);
  const withVol = cs.filter((c) => c.v > 0);
  const primary = withVol[0] || { kw: p.primaryKeyword || cs[0]?.kw, v: 0, kd: null, intent: null };
  const intents = new Set(withVol.map((c) => c.intent));
  const commercial = withVol.some((c) => c.intent === "commercial" || c.intent === "transactional");
  const flags = [];
  if ((p.type === "pillar" || p.type === "hub") && withVol.length && !commercial) flags.push("intent-mismatch (money page ranks only informational)");
  if (p.answerDepth && p.answerDepth.score < 90) flags.push(`answer-depth ${p.answerDepth.score}`);
  return { ...p, cs, withVol, primary, addressable: withVol.reduce((s, c) => s + c.v, 0), commercial, flags };
});

// every keyword's "owner" = the page where it has highest relevance (it's a candidate)
const ownerOf = {};
for (const p of pages) for (const c of p.withVol) if (!ownerOf[c.kw] || p.addressable > ownerOf[c.kw].addr) ownerOf[c.kw] = { url: p.url, addr: p.addressable, isPrimary: p.primary.kw === c.kw };
// opportunities = volume keywords that are nobody's PRIMARY
const primaries = new Set(pages.map((p) => p.primary.kw));
const opps = Object.entries(M).filter(([k, d]) => d.v > 0 && !primaries.has(k))
  .map(([k, d]) => ({ kw: k, ...d, owner: ownerOf[k]?.url || "— (no page targets it)" }))
  .sort((a, b) => b.v - a.v);

const fmtKd = (k) => (k == null ? "—" : k);
// ---- keyword-audit.md ----
let a = `# Healthypets — Keyword Audit (NZ)\n\n`;
a += `Market: **New Zealand / English**. Source: on-page candidates (content/**/*.mdx + hubs/tools) scored via DataForSEO Labs (NZ). Generated by scripts/keyword-extract + keyword-report.\n\n`;
const counts = pages.reduce((m, p) => ((m[p.type] = (m[p.type] || 0) + 1), m), {});
a += `**Pages:** ${pages.length} (${Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(", ")}) · **candidate keywords:** ${cand.uniqueKeywords.length} · **with NZ volume:** ${Object.values(M).filter((d) => d.v > 0).length}\n\n`;
a += `| Page | Type | Primary keyword (chosen) | Vol | KD | Intent | Addressable vol | Top secondary | Flags |\n|---|---|---|--:|--:|---|--:|---|---|\n`;
for (const p of pages.sort((x, y) => y.addressable - x.addressable)) {
  const sec = p.withVol.slice(1, 4).map((c) => `${c.kw} (${c.v})`).join("; ") || "—";
  a += `| ${p.url} | ${p.type} | ${p.primary.kw} | ${p.primary.v || 0} | ${fmtKd(p.primary.kd)} | ${p.primary.intent || "—"} | ${p.addressable} | ${sec} | ${p.flags.join("; ") || "—"} |\n`;
}
fs.writeFileSync("keyword-audit.md", a);

// ---- keyword-opportunities.md ----
let o = `# Healthypets — Keyword Opportunities (NZ)\n\n`;
o += `Keywords with measured NZ demand that are **not the primary target of any page** — either better surfaced on an existing page, or a content gap. Ranked by volume. KD = difficulty (— = not measured; Labs under-reports commercial head terms).\n\n`;
o += `## Already on a page (lift it to primary / strengthen on-page)\n\n| Keyword | Vol | KD | Intent | Best existing page |\n|---|--:|--:|---|---|\n`;
for (const x of opps.filter((x) => !x.owner.startsWith("—")).slice(0, 40)) o += `| ${x.kw} | ${x.v} | ${fmtKd(x.kd)} | ${x.intent || "—"} | ${x.owner} |\n`;
o += `\n## Gaps — no page targets these (new content / new tool)\n\n| Keyword | Vol | KD | Intent |\n|---|--:|--:|---|\n`;
for (const x of opps.filter((x) => x.owner.startsWith("—")).slice(0, 30)) o += `| ${x.kw} | ${x.v} | ${fmtKd(x.kd)} | ${x.intent || "—"} |\n`;
fs.writeFileSync("keyword-opportunities.md", o);

// ---- merged json ----
fs.writeFileSync("keyword-candidates.json", JSON.stringify({ market: "New Zealand", pages: pages.map((p) => ({ url: p.url, type: p.type, primary: p.primary, addressable: p.addressable, flags: p.flags, candidates: p.cs })), opportunities: opps }, null, 2));

console.log("wrote keyword-audit.md, keyword-opportunities.md, keyword-candidates.json");
console.log("intent-mismatch / answer-depth flagged pages:", pages.filter((p) => p.flags.length).map((p) => `${p.url} [${p.flags.join("; ")}]`).join(" | ") || "none");
console.log("top 12 opportunities:", opps.slice(0, 12).map((x) => `${x.kw}(${x.v}${x.owner.startsWith("—") ? ",GAP" : ""})`).join(", "));
